version: '3'
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.19.220.0/24
services:
  psql:
    image: postgres:13.14
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=psqldb
      - POSTGRES_USER=llm
      - POSTGRES_PASSWORD=llm
      - PGDATA=/var/lib/postgresql/data/db-files/
    volumes:
      - llm_psql_volume:/var/lib/postgresql/data
  llm-app-backend:
    image: local/llm-app-backend:latest
    restart: unless-stopped
    links:
      - psql:psql
      - payload:payload
    ports:
      - 8081:80
    volumes:
      - llm_config_volume:/app/config
    # healthcheck:
    #   test: curl --fail http://localhost/api/ui/alive || kill 1
    #   interval: 60s
  llm-app-ui:
    image: local/llm-app-ui:latest
    restart: unless-stopped
    ports:
      - 8082:80
    healthcheck:
      test: curl --fail http://localhost || kill 1
      interval: 60s
  payload:
    image: local/payload:latest
    restart: unless-stopped
    ports:
      - 8083:8080
    healthcheck:
      test: curl --fail http://localhost:8000 || kill 1
      interval: 60s
  proxy:
    image: local/proxy:latest
    restart: unless-stopped
    links:
      - llm-app-backend:llm-app-backend
      - llm-app-ui:llm-app-ui
    ports:
      - 8085:80
    volumes:
      - llm_proxy_config:/opt/bitnami/openresty/nginx/conf/
    healthcheck:
      test: curl --fail http://localhost || kill 1
      interval: 60s
volumes:
  llm_psql_volume: { }
  llm_config_volume: { }
  llm_proxy_config: { }
